name: Run Python Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-pytest:
    uses: George-Ogden/actions/.github/workflows/python-test.yaml@v4.0.2
    with:
      python-versions: "['3.11', '3.12', '3.13', '3.14']"
